version: "2.2"
services:
    kue:
      image: 'valentinvieriu/booksclub:kue-1.0.1'
      build: .
      restart: always
      environment:
        PORT: 9000
        REDIS_URL: ${REDIS_URL}
      # ports: 
      #   - "9000:9000"
